const STORIES={
fairy:[
{i:'🌙',ko:['달빛을 모으는 예린','예린이는 창가에 앉아 작은 유리병을 들었어요. 달빛은 포근한 우유처럼 방 안으로 흘러들었지요. “달빛아, 우리 친구 할래?” 은빛 조각이 병 속에서 반짝였어요. 예린이는 그 빛을 밤을 무서워하는 토끼에게 나누어 주었고, 둘은 환한 방에서 웃으며 잠이 들었답니다.','작은 빛도 나누면 큰 용기가 돼요.'],en:['Yerin and the Jar of Moonlight','Yerin sat by the window with a tiny glass jar. Moonlight flowed into the room like warm milk. “Moonlight, will you be my friend?” A silver glow danced inside the jar. Yerin shared it with a rabbit who was afraid of the dark, and the two friends fell asleep with peaceful smiles.','A little light becomes great courage when we share it.']},
{i:'🌱',ko:['예린이의 말하는 씨앗','예린이는 화분에 작은 씨앗을 심고 매일 다정하게 인사했어요. “안녕, 오늘도 기다릴게.” 어느 아침 흙 속에서 목소리가 들렸어요. “천천히 자라도 괜찮다고 말해 줘.” 예린이는 물과 햇볕을 선물했고, 며칠 뒤 초록 잎과 함께 기다림이라는 꽃이 마음에 피었답니다.','천천히 자라는 시간도 소중해요.'],en:['Yerin and the Talking Seed','Yerin planted a tiny seed and greeted it kindly every day. “Hello. I will wait for you.” A little voice asked her to be patient. Yerin gave it water and sunshine. Soon a green leaf appeared, and patience blossomed in her heart.','Growing slowly is still beautiful.']}],
song:[
{i:'🎵',ko:['예린이의 반짝반짝 아침','반짝반짝 햇살이, 예린이 볼에 톡톡톡. 기지개를 쭉 펴고, 좋은 아침 안녕! 콩콩 뛰는 작은 발, 웃음꽃이 활짝짝. 오늘 만날 모든 것, 사랑으로 안녕!','밝은 인사는 하루를 노래로 만들어요.'],en:['Yerin’s Shiny Morning','Shiny, shiny morning sun, taps on Yerin one by one. Stretch up high and touch the sky. Hello, morning! Here am I! Little footsteps hop, hop, hop. Smiles are blooming, never stop.','A cheerful hello turns the day into a song.']},
{i:'⭐',ko:['별 하나 마음 하나','별 하나 반짝이면 예린 마음 두근두근. 별 둘이 손잡으면 우리 마음 포근포근. 잘 자라 오늘 하루, 꿈나라로 사뿐사뿐. 사랑해 우리 예린, 아침까지 반짝반짝.','사랑받는 마음은 밤새 환하게 빛나요.'],en:['One Star, One Heart','One star twinkles in the night. Yerin’s heart is warm and bright. Two stars hold hands in the sky. Sleep now, Yerin, dreams are near. You are loved, my little dear.','A loved heart shines all through the night.']}],
aesop:[
{i:'🦁',ko:['예린이와 사자의 약속','숲길에서 예린이는 발에 가시가 박힌 사자를 만났어요. 가시를 빼 주자 사자는 “네가 어려울 때 나도 도울게”라고 약속했어요. 얼마 뒤 깊은 웅덩이 앞에서 곤란해진 예린이에게 사자는 커다란 나무를 다리처럼 놓아 주었어요. 크기가 달라도 서로 도울 수 있다는 것을 둘은 배웠답니다.','친절은 언젠가 다른 모습으로 돌아와요.'],en:['Yerin and the Lion’s Promise','Yerin found a lion with a thorn in his paw and gently pulled it out. The lion promised to help her one day. Later, he placed a fallen tree across a deep ditch so Yerin could cross. They learned that friends of every size can help one another.','Kindness often finds its way back to us.']},
{i:'🐢',ko:['예린이와 천천히 걷는 거북이','예린이는 빨리 달리는 토끼만 멋지다고 생각했어요. 하지만 숲길 대회에서 토끼는 갈림길을 지나쳤고, 거북이는 표지판을 하나씩 살펴 바른 길을 찾았지요. 예린이는 거북이와 천천히 걸어 목적지에 도착했답니다.','꾸준함과 주의 깊은 마음은 든든한 힘이에요.'],en:['Yerin and the Careful Tortoise','Yerin thought only the fast rabbit was impressive. But the rabbit rushed past a turn. The tortoise studied every sign, and Yerin walked carefully beside him. Together they found the finish.','Patience and attention are quiet superpowers.']}],
myth:[
{i:'🧵',ko:['예린이와 아리아드네의 실','크레타섬의 미로 앞에서 예린이는 아리아드네를 만났어요. 아리아드네는 황금빛 실을 주며 “용기만큼 돌아올 길을 기억하는 지혜도 중요해”라고 말했어요. 예린이는 실을 묶고 미로 속 새끼 염소를 구한 뒤, 반짝이는 실을 따라 무사히 돌아왔답니다.','용기는 지혜와 함께할 때 더 빛나요.'],en:['Yerin and Ariadne’s Thread','At the maze of Crete, Ariadne gave Yerin a golden thread. “Courage matters, but so does remembering the way home.” Yerin rescued a lost little goat and followed the shining thread safely home.','Courage shines brightest when guided by wisdom.']},
{i:'☀️',ko:['예린이와 아폴론의 작은 리라','음악의 신 아폴론은 속상한 예린이에게 작은 리라를 빌려주었어요. “완벽한 노래보다 네 마음의 소리를 들려주렴.” 예린이가 천천히 연주하자 바람과 새들이 화음을 넣었어요. 슬픈 마음도 누군가를 위로하는 노래가 될 수 있었답니다.','마음을 솔직하게 표현하면 위로가 시작돼요.'],en:['Yerin and Apollo’s Little Lyre','Apollo lent Yerin a little lyre. “Do not play a perfect song. Play the sound of your heart.” Birds and breezes joined her melody, and Yerin learned that even sadness can become a song of comfort.','Honest feelings can begin a song of healing.']} ]};
const $=function(s){return document.querySelector(s)}, $$=function(s){return Array.from(document.querySelectorAll(s))};
const AGES=['0세 · 소리와 리듬','1세 · 짧은 낱말','2세 · 반복 문장','3세 · 쉬운 이야기','4세 · 상상 이야기','5세 · 마음과 선택','6세 · 모험과 교훈','7세 · 깊이 생각하기'];
let state={lang:'ko',cat:'fairy',index:0,age:4,name:localStorage.getItem('yelin-name')||'예린',voice:null};
function init(){AGES.forEach(function(x,i){$('#age').add(new Option(x,i));$('#parentAge').add(new Option(x,i))});$('#age').value=state.age;$('#name').value=$('#parentName').value=state.name;bind();loadVoices();render()}
function bind(){$$('.lang').forEach(function(b){b.onclick=function(){state.lang=b.dataset.lang;$$('.lang').forEach(function(x){x.classList.toggle('active',x===b)});loadVoices();render()}});$$('.cat').forEach(function(b){b.onclick=function(){state.cat=b.dataset.cat;state.index=0;$$('.cat').forEach(function(x){x.classList.toggle('active',x===b)});render()}});$('#age').onchange=function(e){state.age=+e.target.value;render()};$('#name').onchange=function(e){setName(e.target.value)};$('#voice').onchange=function(e){state.voice=speechSynthesis.getVoices().find(function(v){return v.name===e.target.value})};$('#play').onclick=play;$('#pause').onclick=pause;$('#stop').onclick=stop;$('#settings').onclick=function(){$('#dialog').showModal()};$('#saveSettings').onclick=function(){setName($('#parentName').value);state.age=+$('#parentAge').value;$('#age').value=state.age};$('#record').onclick=record;$('#delete').onclick=removeRecording}
function setName(v){state.name=(v||'예린').trim();$('#name').value=$('#parentName').value=state.name;localStorage.setItem('yelin-name',state.name);render()}
function named(v){return v.split('예린').join(state.name).split('Yerin').join(state.name==='예린'?'Yerin':state.name)}
function current(){return STORIES[state.cat][state.index][state.lang]}
function adapted(v){const a=v.split(/(?<=[.!?]|어요\.|답니다\.|지요\.)\s+/);return state.age<=1?a.slice(0,2).join(' '):state.age===2?a.slice(0,3).join(' '):state.age<=4?a.slice(0,4).join(' '):v}
function render(){stop();const arr=STORIES[state.cat];$('#list').innerHTML=arr.map(function(x,i){return '<button class="story '+(i===state.index?'active':'')+'" data-i="'+i+'"><i>'+x.i+'</i><span><b>'+named(x[state.lang][0])+'</b><small>'+(state.lang==='ko'?AGES[state.age]:'Age '+state.age)+'</small></span></button>'}).join('');$$('[data-i]').forEach(function(b){b.onclick=function(){state.index=+b.dataset.i;render()}});const d=current();$('#hello').textContent=state.name;$('#badge').textContent={fairy:'따뜻한 창작동화',song:'함께 부르는 동요',aesop:'오늘의 이솝 지혜',myth:'어린이를 위한 그리스신화'}[state.cat];$('#title').textContent=named(d[0]);$('#subtitle').textContent=state.lang==='ko'?state.age+'세 눈높이 이야기 · 약 2분':'Age '+state.age+' story · about 2 min';$('#text').textContent=adapted(named(d[1]));$('#lesson').textContent=named(d[2]);loadRecording()}
function loadVoices(){const vs=speechSynthesis.getVoices().filter(function(v){return state.lang==='ko'?v.lang.indexOf('ko')===0:v.lang.indexOf('en')===0});$('#voice').innerHTML='';vs.forEach(function(v){$('#voice').add(new Option(v.name+' · '+v.lang,v.name))});state.voice=vs.find(function(v){return /Natural|Google|Microsoft|Siri/i.test(v.name)})||vs[0];if(state.voice)$('#voice').value=state.voice.name;if(!vs.length)$('#voice').add(new Option(state.lang==='ko'?'기기 기본 한국어 목소리':'Device default English voice',''))}
speechSynthesis.onvoiceschanged=loadVoices;
function play(){if(!$('#audio').hidden&&$('#audio').src){$('#audio').play();return}stop();const u=new SpeechSynthesisUtterance($('#text').textContent);u.lang=state.lang==='ko'?'ko-KR':'en-US';u.rate=+$('#rate').value;u.pitch=state.lang==='ko'?.92:1;if(state.voice)u.voice=state.voice;speechSynthesis.speak(u)}
function pause(){if(speechSynthesis.speaking){speechSynthesis.paused?speechSynthesis.resume():speechSynthesis.pause()}else $('#audio').pause()}
function stop(){speechSynthesis.cancel();if($('#audio')){$('#audio').pause();$('#audio').currentTime=0}}
let mediaRecorder,chunks=[],recording=false;
async function record(){if(recording){mediaRecorder.stop();return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});mediaRecorder=new MediaRecorder(stream);chunks=[];mediaRecorder.ondataavailable=function(e){chunks.push(e.data)};mediaRecorder.onstop=function(){const reader=new FileReader();reader.onload=function(){try{localStorage.setItem(recordKey(),reader.result);loadRecording()}catch(e){$('#recordStatus').textContent='녹음이 길어 저장공간이 부족해요.'}};reader.readAsDataURL(new Blob(chunks,{type:'audio/webm'}));stream.getTracks().forEach(function(t){t.stop()});recording=false;$('#record').textContent='● 다시 녹음';$('#recordStatus').textContent='녹음 저장 완료'};mediaRecorder.start();recording=true;$('#record').textContent='■ 녹음 끝내기';$('#recordStatus').textContent='부모님 목소리를 녹음하고 있어요…'}catch(e){$('#recordStatus').textContent='마이크 사용을 허용해 주세요.'}}
function recordKey(){return 'yelin-audio-'+state.cat+'-'+state.index+'-'+state.lang+'-'+state.age}
function loadRecording(){const src=localStorage.getItem(recordKey());$('#audio').hidden=$('#delete').hidden=!src;if(src)$('#audio').src=src;else $('#audio').removeAttribute('src')}
function removeRecording(){localStorage.removeItem(recordKey());loadRecording();$('#recordStatus').textContent='녹음을 삭제했어요.'}
init();
